# Azure Tester
trigger: 
- master # Triggers when on master. Either pr or push

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04

jobs:

- job: linux
  pool:
    vmImage: 'Ubuntu 16.04'
  container: bionic
  steps:
  - template: azure-init.yml
  - script: git submodule update --init
  - script: git submodule update --remote -f
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio -PdebugMode'

- job: windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-init.yml
  - script: git submodule update --init
  - script: git submodule update --remote -f
    displayName: 'Download JDK'
  # - task: Gradle@2
  #   inputs:
  #     workingDirectory: ''
  #     gradleWrapperFile: 'gradlew'
  #     gradleOptions: '-Xmx2048'
  #     publishJUnitResults: false
  #     tasks: 'downloadAll'
  #     options: '-Pno-roborio -PdebugMode'
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      options: '-Pno-roborio -PdebugMode'
      tasks: 'clean build'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072'
      sonarQubeRunAnalysis: false

  


# - job: Mac
#   pool:
#     vmImage: 'macOS-10.14'

#   steps:
#     - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
#       submodules: true
#     - script: |
#         mkdir build
#         export JAVA_HOME=`/usr/libexec/java_home -v 11`
#         brew install ant binutils
#       displayName: 'Setup JDK Ant and Binutils'
#     - task: Gradle@2
#       inputs:
#         workingDirectory: ''
#         gradleWrapperFile: 'gradlew'
#         gradleOptions: '-Xmx3072m'
#         jdkVersionOption: '1.11'
#         publishJUnitResults: false
#         testResultsFiles: '**/TEST-*.xml'
#         tasks: 'clean build'
#         options: '-Pno-roborio -PdebugMode'