# Azure Tester
trigger: 
- master

jobs:

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build -PdebugMode'

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build -PdebugMode'

- job: linux
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt-get install -y libusb-1.0-0-dev
  - script: sudo wget -qO - https://github.com/CJBuchel/CJ-Vision/blob/2.0/bootstrap/openCV.sh?raw=1 | bash
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build -PdebugMode'