# Azure Tester
trigger: 
- master # Triggers when on master. Either pr or push

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04

jobs:

- job: linux
  pool:
    vmImage: 'Ubuntu 16.04'
  container: bionic
  steps:
  - checkout: self
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'
      options: '-Pno-roborio -PdebugMode'

- job: windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
  - template: azure-init.yml
  - powershell: |
      mkdir build
      $ProgressPreference = 'SilentlyContinue'
      wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
    displayName: 'Download JDK'
  - task: JavaToolInstaller@0
    inputs:
      jdkSourceOption: localDirectory
      jdkFile: 'build/jdk.zip'
      jdkDestinationDirectory: 'build/jdkinst'
      jdkArchitectureOption: x64
  - script: |
      @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
      set PATH=%PATH%;%ANT_HOME%\bin
      gradlew build -Pno-roborio -PdebugMode
    displayName: 'Gradle Build'
  
  # - task: Gradle@2
  #   inputs:
  #     workingDirectory: ''
  #     gradleWrapperFile: 'gradlew'
  #     gradleOptions: '-Xmx3072m'
  #     publishJUnitResults: false
  #     testResultsFiles: '**/TEST-*.xml'
  #     tasks: 'clean build'
  #     options: '-Pno-roborio -PdebugMode'


# - job: macOS
#   pool:
#     vmImage: 'macOS-latest'
#   steps:
#   - template: azure-init.yml
#   - task: Gradle@2
#     inputs:
#       workingDirectory: ''
#       gradleWrapperFile: 'gradlew'
#       gradleOptions: '-Xmx3072m'
#       publishJUnitResults: false
#       testResultsFiles: '**/TEST-*.xml'
#       tasks: 'clean build -PdebugMode'