# Azure Tester
trigger: 
- master # Triggers when on master. Either pr or push

jobs:

- job: windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure-init.yml
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'installRoboRioToolchain'
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build -PdebugMode'

# - job: macOS
#   pool:
#     vmImage: 'macOS-latest'
#   steps:
#   - template: azure-init.yml
#   - task: Gradle@2
#     inputs:
#       workingDirectory: ''
#       gradleWrapperFile: 'gradlew'
#       gradleOptions: '-Xmx3072m'
#       publishJUnitResults: false
#       testResultsFiles: '**/TEST-*.xml'
#       tasks: 'clean build -PdebugMode'